version: '3'
services:
  python3:
    restart: always
    build: .
    ports:
      - "80:5000"
    container_name: 'flask'
    working_dir: '/root/src'
    tty: true
    volumes:
      - ${SRC_PATH}:/root/src
